# Generated by Django 3.2.9 on 2022-02-04 12:37

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_alert', models.DateField(auto_now=True)),
                ('second_alert', models.DateField(auto_now=True)),
                ('due_date', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='DrugBatch',
            fields=[
                ('batch_no', models.CharField(max_length=10)),
                ('drug_types', models.CharField(max_length=255)),
                ('total_cost', models.DecimalField(decimal_places=2, max_digits=8, validators=[django.core.validators.MinValueValidator(1)])),
                ('inventory', models.CharField(max_length=255, validators=[django.core.validators.MinValueValidator(1)])),
                ('expiry_date', models.DateField(auto_now=True)),
                ('alert', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='main.alert')),
            ],
        ),
        migrations.CreateModel(
            name='Drug',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('price', models.DecimalField(decimal_places=2, max_digits=6, validators=[django.core.validators.MinValueValidator(1)])),
                ('desription', models.TextField()),
                ('expiry_date', models.DateField(auto_now=True)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.drugbatch')),
            ],
        ),
    ]
